import { IParams } from "../types/email";


const nodemailer = require("nodemailer");

class EmailUtil {
  constructor() {}

  sendMailAsync = async (params: IParams) => {
    return new Promise((resolve, reject) => {
      const transporter = nodemailer.createTransport({
        service: "gmail",
        auth: {
          user: process.env.USER_EMAIL, //generated by Mailtrap
          pass: process.env.EMAIL_PASSWORD, //generated by Mailtrap
        },
      });

      var mailOptions = {
        from: params.fromEmail,
        to: params.destinationEmail,
        subject: params.subject,
        text: params.text,
        html: params.html,
      };

      transporter.sendMail(mailOptions, function (error: any, info: any) {
        if (error) {
          console.log("error is " + error);
          resolve(false); // or use rejcet(false) but then you will have to handle errors
        } else {
          console.log("Email sent: " + info.response);
          resolve(true);
        }
      });
    });
  };

  receiveEmailContact = (params: IParams, callback: any) => {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.USER_EMAIL, //generated by Mailtrap
        pass: process.env.EMAIL_PASSWORD, //generated by Mailtrap
      },
    });

    let option = {
      from: params.fromEmail,
      to: "trifinourdine07@gmail.com", // params.destinationEmail,
      subject: params.subject,
      text: params.text,
      html: `<h1>Nom du client : ${params.text}</h1>
            <p>le numéro est ${params.subject}</p> et le message est : ${params.html}`,
    };

    console.log("option send email:", option);
    transporter.sendMail(option, callback);
  };

  sendSignupConfirmationEmail = async (clientEmail: string) => {
    const from = "trifinourdine07@gmail.com";
    const text =
      "Vous venez de valider votre inscription chez la plateforme CoWork !";

    await this.sendMailAsync({
      fromEmail: from,
      destinationEmail: clientEmail,
      subject: "Validation de l'inscription",
      text: "" + text,
      html: `<h4>Bonjour cher client, votre profil a été validée nous vous invitons 
        à vous reconnecter sur le site et à finaliser votre inscription afin de pouvoir bénéficier de nos offres !</h4>
        <br> <p>Vous pouvez vous connecter directement sur le site</p> <a>http://localhost:4200/login</a>`,
    });
  };
}
export default EmailUtil;
